deepspeed --master_port 29500 --include localhost:0,1 src/train.py \
    --sample_weights balance \
    --use_history True \
    --num_workers 2 \
    --prompt_type rt1_default \
    --text_enc /data1/hyx/huggingface/jina-embeddings-v2-base-en \
    --method rt1 \
    --train_batch_size 128 \
    --gradient_accumulation_steps 2 \
    --eval_batch_size 32 \
    --max_lr 1e-4 \
    --steps 100000 \
    --warmup_steps 3000 \
    --log_interval 500 \
    --eval_interval 2000 \
    --save_interval 2000 \
    --save_dir rt1_aug_save \
    --random_seed 42
