deepspeed --include localhost:2,3 src/train.py \
    --sample_weights balance \
    --num_workers 2 \
    --method gc_bc \
    --steps 100000 \
    --warmup_steps 3000 \
    --log_interval 2500 \
    --eval_interval 5000 \
    --save_interval 5000 \
    --save_dir gcbc_aug_save \
    --random_seed 42